// playground/react/src/components/IFrameEmbed.tsx
import React from 'react';

// Assuming blok prop is an object that contains an url object which, in turn, contains the actual URL string
interface BlokType {
  url: {
    url: string;
  };
}

interface Props {
  blok: BlokType; // Defining the expected shape of the 'blok' prop
}

const IFrameEmbed: React.FC<Props> = ({ blok }) => {
  return (
    <iframe
      src={blok.url.url}
      className="w-full aspect-video"
      frameBorder="0"
    >
    </iframe>
  );
};

export default IFrameEmbed;

// playground/svelte/src/IFrameEmbed.svelte
<script lang="ts">
  export let blok: { url: { url: string } };
</script>

<iframe src={blok.url.url} class="w-full aspect-video" frameborder="0" title=""></iframe>

<style>
  .w-full {
    width: 100%;
  }
  .aspect-video {
    aspect-ratio: 16 / 9; /* Adjust as necessary for the desired aspect ratio */
  }
</style>
